---
output: html_document
params:
  data: NA
  study: NA
  first_date: NA
  number_events: NA 
  milestone: NA
---

```{r setup, include=FALSE, message = FALSE}
library(shiny)
library(shinythemes)
library(tidyverse)
library(flexsurv)
library(quadprog)
library(Hmisc)
library(msm) 
library(VGAM)
library(ggplot2)
library(scales)
library(knitr)
library(kableExtra)

data <- params$data
study <- params$study
first_date <- params$first_date
number_events <- params$number_events
milestone <- params$milestone
today <- Sys.Date()
```


```{r, echo=FALSE}
table <- tribble(
  ~colA                            , ~colB,
  paste0("Study: ",study)           , "",
  paste0("Date of first patient enrolled: ", first_date), paste0("Date prediction was carried out: ", today),
  paste0("Number fo events: ", number_events)              , paste0("Number of event predicted (milestone):", milestone )
) %>%
  setNames(c("",""))

kable(table, "html") %>%
  kable_styling(full_width = T) %>%
  column_spec(1, border_left = FALSE, border_right = FALSE, underline = FALSE) %>%
  column_spec(2, border_left = FALSE, border_right = FALSE, underline = FALSE) %>%
  row_spec(1, underline = FALSE) %>%
  row_spec(2, underline = FALSE)
```

## Predicted milestone date
```{r, echo=FALSE}
group.colors <- c(A = "#2ca25f", B = "#636363")
p <- ggplot(data, aes(x = mean, y = label, xmin = lower, xmax = upper, color = color)) +
      geom_pointrangeh() +
      theme(legend.position="none") +
      scale_color_manual(values=group.colors) +
      facet_grid(type ~ ., scale = "free", switch="both") + 
      scale_x_date(labels = date_format("%Y-%m-%d")) +
      labs(y = "Days since first patient enrolled", x = "")
    p
```

```{r, echo = FALSE}
all <- data %>%
  mutate(method = case_when(
    method == "Bayes-Gompertz" ~ "Gompertz",
    method == "Bayes-LogLogistic" ~ "Log-Logistic",
    method == "Bayes-LogNormal" ~ "Log-Normal",
    method == "Bayes-PredSyn(Avg)" ~ "Predicitive Synthesis (Average)",
    method == "Bayes-PredSyn(MSPE)" ~ "Predicitive Synthesis (MSPE)",
    method == "Bayes-PredSyn(Vote)" ~ "Predicitive Synthesis (Vote)",
    method == "Bayes-Weibull" ~ "Weibull",
    method == "Freq-Gompertz" ~ "Gompertz",
    method == "Freq-LogLogistic" ~ "Log-Logistic",
    method == "Freq-LogNormal" ~ "Log-Normal",
    method == "Freq-PredSyn(Avg)" ~ "Predicitive Synthesis (Average)",
    method == "Freq-PredSyn(MSPE)" ~ "Predicitive Synthesis (MSPE)",
    method == "Freq-PredSyn(Vote)" ~ "Predicitive Synthesis (Vote)",
    method == "Freq-Weibull" ~ "Weibull"),
        order = c(4,5,7,6,2,1,3,8,10,14,12,4,2,6)) %>%
      arrange(order) %>% 
  select(method, lower, mean, upper, type) %>%
  setNames(c("Method", "Lower bound", "Prediction", "Upper bound", "type"))


freq <- filter(all, type == "Bayesian") %>% 
      select(-type)
bayes <- filter(all, type == "Frequentist") %>% 
      select(-type)
  
```

## Bayesian method

```{r, echo=FALSE}

kable(bayes, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```


## Frequentist method
```{r, echo=FALSE}

kable(freq, "html") %>%
  kable_styling(bootstrap_options = c("striped", "hover"))

```
